builders:
  partBuilder:
    import: "package:generated_part_issue_repro/src/builder.dart"
    builder_factories: ["partBuilder"]
    build_extensions: {".dart" : [".g.dart"]}
    auto_apply: none
    build_to: cache

targets:
  $default:
    builders:
      generated_part_issue_repro|partBuilder:
        enabled: true
        generate_for:
          include:
            - "example/**"
