builders:
  buildPartToSourceBuilder:
    import: "package:generated_part_issue_repro/src/builder.dart"
    builder_factories: ["buildPartToSourceBuilder"]
    build_extensions: {".dart" : [".g.dart"]}
    auto_apply: none
    build_to: cache

targets:
  $default:
    builders:
      generated_part_issue_repro|buildPartToSourceBuilder:
        enabled: true
        generate_for:
          include:
            - "example/**"
