name: generated_part_issue_repro
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build:

dev_dependencies:
  build_runner:
  build_web_compilers:
