// If this file has a library name, the part generated by the builder will
// use the library name in its `part of`, as opposed to a path.
library lib.foo_library;

// There are no errors for this part.
part 'library_part_of.g.dart';

main() {
  // This reference resolves properly (you can jump to definition in IDEs).
  print(_$generatedMember);
}
