// If this file does not has a library name, the part generated by the builder will
// use a path its `part of`.

// After a build, this part directive has no error, but would if this file were not in lib.
part 'path_part_of.g.dart';

main() {
  print(_$generatedMember);
}
