name: Dart CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - 2.15.1 # Last version with no errors
          - 2.16.0 # First version with uri_has_not_been_generated errors
          - 2.17.7 # Last version with uri_has_not_been_generated errors
          - 2.18.0 # First version with part_of_different_library error
          - stable
          - beta
          - dev
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print Dart SDK version
        run: dart --version

      - id: install
        name: Install dependencies
        run: dart pub get

      - id: build
        name: Build generated Dart files
        run: dart run build_runner build --build-filter='**.dart'

      - name: Analyze project source (post-build)
        run: dart analyze .

      - id: js-compile
        name: Compile to DDC and dart2js
        run: dart run build_runner build && dart run build_runner build --release
        if: always()

      - name: Execute entrypoint - generated part uses library name in `part of`
        run: dart run build_runner run example/with_generated_part/library_part_of.dart
        if: always()

      - name: Execute entrypoint - generated part uses URI in `part of`
        run: dart run build_runner run example/with_generated_part/path_part_of.dart
        if: always()
